<%@ page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" %>
<html lang="en">
  <head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Mahindra XUV.e9 | CarVerse</title><link rel="stylesheet" href="assets/css/carverse.css"></head>
  <body>
    <nav class="nav"><div class="shell"><a class="brand" href="index.jsp">CARVERSE</a><div class="navlinks"><a href="index.jsp">Explore</a><a class="active" href="car-search.jsp">New Cars</a><a href="compare.jsp">Compare</a><a href="index.jsp#ownership">Ownership</a></div><a href="login.jsp">Sign in</a><a class="btn btn-primary" href="user_registration.html">Get started →</a></div></nav>
    <main class="details-page"><div class="shell">
      <div class="breadcrumbs"><a href="index.jsp">Home</a><span>/</span><a href="car-search.jsp">New cars</a><span>/</span> Mahindra XUV.e9</div>
      <section class="detail-hero"><div class="detail-gallery"><img class="primary-car-image" src="https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=85" alt="Mahindra XUV.e9"><div class="gallery-thumbs"><button class="selected">Exterior</button><button>Interior</button><button>Colours</button><button>360°</button></div></div><div class="detail-summary"><span class="tag">Electric coupe SUV</span><h1>Mahindra XUV.e9</h1><p class="rating"><b>4.6</b> ★★★★★ <a href="#reviews"> 128 reviews</a></p><div class="detail-price">₹21.90 - 30.50 Lakh<sup>*</sup></div><p class="on-road">Get on-road price for Delhi</p><div class="offer-inline">⌁ Limited-time benefit up to <strong>₹75,000</strong></div><div class="detail-ctas"><a class="btn btn-primary" href="#offers">View offers →</a><button class="btn btn-outline" data-toast="Test-drive request saved. We'll contact you shortly.">Book a test drive</button></div><p class="fine-print">*Ex-showroom price. Terms and conditions apply.</p></div></section>
      <nav class="detail-tabs"><a class="active" href="#overview">Overview</a><a href="#specifications">Specifications</a><a href="#offers">Offers</a><a href="#variants">Variants</a><a href="#reviews">Reviews</a></nav>
      <div class="detail-layout"><div>
        <section class="detail-section" id="overview"><div class="eyebrow">At a glance</div><h2>Designed to go further.</h2><p class="sub">The XUV.e9 brings a sleek coupe-SUV profile, a roomy five-seat cabin and a long certified range to everyday electric driving.</p><div class="highlights"><div><span>⚡</span><strong>656 km</strong><small>Certified range</small></div><div><span>▣</span><strong>79 kWh</strong><small>Battery capacity</small></div><div><span>↯</span><strong>6.8 sec</strong><small>0–100 km/h</small></div><div><span>◌</span><strong>5 seats</strong><small>Seating capacity</small></div></div></section>
        <section class="detail-section" id="specifications"><div class="section-head"><div><div class="eyebrow">Know the essentials</div><h2>Key specifications</h2></div><a class="text-link" href="#">View all specifications →</a></div><div class="details-spec-grid"><div><span>Powertrain</span><b>Electric</b></div><div><span>Transmission</span><b>Automatic</b></div><div><span>Drive type</span><b>Rear-wheel drive</b></div><div><span>Charging time</span><b>20 min (DC fast)</b></div><div><span>Boot space</span><b>663 litres</b></div><div><span>Safety rating</span><b>★★★★★</b></div></div></section>
        <section class="detail-section" id="variants"><div class="eyebrow">Choose your variant</div><h2>XUV.e9 variants & pricing</h2><div class="variant-list"><label class="variant active"><input type="radio" name="variant" checked><span><b>Pack One</b><small>59 kWh · 542 km range</small></span><strong>₹21.90 Lakh*</strong></label><label class="variant"><input type="radio" name="variant"><span><b>Pack Two</b><small>79 kWh · 656 km range</small></span><strong>₹25.75 Lakh*</strong></label><label class="variant"><input type="radio" name="variant"><span><b>Pack Three</b><small>79 kWh · AWD · 656 km range</small></span><strong>₹30.50 Lakh*</strong></label></div></section>
      </div><aside class="sticky-side" id="offers"><section class="offer-card"><div class="eyebrow">Offers for Delhi</div><h2>Unlock your best price.</h2><div class="offer-row"><span>Cash benefit</span><b>Up to ₹50,000</b></div><div class="offer-row"><span>Exchange bonus</span><b>Up to ₹25,000</b></div><div class="offer-row"><span>EMI from</span><b>₹44,170/mo</b></div><a class="btn btn-primary" href="login.jsp">Check eligibility →</a><p>Personalised offer details from nearby dealers.</p></section><section class="side-card"><b>Want a closer look?</b><p>Compare the XUV.e9 with your shortlist.</p><a href="compare.jsp">Compare cars →</a></section></aside></div>
      <section class="detail-section review-section" id="reviews"><div class="eyebrow">Owner voices</div><h2>What drivers are saying</h2><div class="review-card"><div class="review-score">4.6 <span>★★★★★</span></div><div><p>“The cabin feels genuinely premium and the real-world range is reassuring for road trips.”</p><b>Rohan S. · Verified owner</b></div></div></section>
    </div></main>
    <footer class="footer"><div class="shell"><div><a class="brand" href="index.jsp">CARVERSE</a><p>Drive your next decision with confidence.</p></div><div>Explore · Compare · Book · Maintenance · Support</div><div>© 2026 CarVerse</div></div></footer><div class="toast"></div><script src="assets/js/carverse.js"></script>
  </body>
</html>
